Merge latest changes into `feature/block-streaming` (#2220)
Merge from block-metadata-catchup, to include changes from #2216 as well as #2205 and #2052.

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -132,9 +132,7 @@ elif [[ -n "$diff" ]]; then
 		echo "Do you want to fix all these files automatically? (y/N) "
 		read YESNO
 		if [[ -n "$YESNO" ]] && [[ "$(echo "${YESNO:0:1}" | tr '[[:lower:]]' '[[:upper:]]')" = "Y" ]]; then
-			echo -e "$diff" | sort -u | while read file; do
-				$CARGOFMT $file
-			done
+			echo -e "$diff" | sort -u | xargs -n 1 $CARGOFMT
 			echo "You should attempt this commit again to pick up these changes."
 		else
 			echo -e "Run ${BOLD}$CARGOFMT -- <file>${NC} to format the files you have staged."
@@ -142,6 +140,45 @@ elif [[ -n "$diff" ]]; then
 		exec <&-
 	else
 		echo -e "Run ${BOLD}$CARGOFMT -- <file>${NC} to format the files you have staged."
+	fi
+else
+	printf "${SUCCESS}\n"
+fi
+
+# Similarly, check if copyright statements are missing and offer to add them if they are
+printf "${PREFIX} Checking copyright statements ... "
+COPYRIGHT_LINE="// Copyright (c) 2018-2022 The MobileCoin Foundation"
+diff=""
+for file in $(git diff --name-only --cached --diff-filter=d | egrep -v '^sgx/sgx_(tcrypto|urts|types)');
+do
+	if [[ ${file: -3} == ".rs" ]]; then
+		if ! [[ $(head -n 1 ${file}) == "${COPYRIGHT_LINE}" ]]
+		then
+		    diff="$file\n$diff"
+		fi
+	fi
+done
+
+if [[ "${SKIP_RUSTFMT}" == 1 ]]; then
+	printf "${SKIPPED}\n"
+elif [[ -n "$diff" ]]; then
+	FAILED=1
+	printf "${FAILURE}\n"
+	echo -e "\033[33;1mFiles Needing Copyright:\033[0m"
+	echo -e "$diff" | sort -u
+	if [[ -n "$(which tty)" ]] && [[ -n "$(tty)" ]]; then
+		exec < /dev/tty
+		echo "Do you want to fix all these files automatically? (y/N) "
+		read YESNO
+		if [[ -n "$YESNO" ]] && [[ "$(echo "${YESNO:0:1}" | tr '[[:lower:]]' '[[:upper:]]')" = "Y" ]]; then
+			echo -e "$diff" | sort -u | xargs -n 1 sed -i "1s;^;${COPYRIGHT_LINE}\n\n;"
+			echo "You should attempt this commit again to pick up these changes."
+		else
+			echo -e "Add copyright statements to the files."
+		fi
+		exec <&-
+	else
+		echo -e "Add copyright statements to the files."
 	fi
 else
 	printf "${SUCCESS}\n"
