Update precommit hook to install/use cargo sort.

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -68,6 +68,28 @@ else
 	printf "${SUCCESS}\n"
 fi
 
+printf "${PREFIX} Checking that cargo-sort is installed..."
+
+cargo sort --version
+if [ $? == 0 ]; then
+	printf "${SUCCESS}\n"
+else
+	printf "${WARNING}, Installing cargo-sort before continuing."
+	cargo install cargo-sort
+	popd >/dev/null 2>&1
+	exit 1
+fi
+
+printf "${PREFIX} Checking that Cargo.toml dependencies are sorted..."
+cargo sort --workspace --grouped --check
+if [ $? == 0 ]; then
+	printf "${SUCCESS}\n"
+else
+	printf "${FAILURE}\n"
+	popd >/dev/null 2>&1
+	exit 1
+fi
+
 printf "${PREFIX} Checking for rustfmt ... "
 cargo fmt --version
 if [ $? == 0 ]; then
